
replicaCount: 3

image:
  repository: 461625527829.dkr.ecr.eu-west-2.amazonaws.com/prod/order-service
  tag: "latest"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  roleArn: arn:aws:iam::461625527829:role/ecommerce-eks-prod-order-service

service:
  port: 8081

secrets:
  postgresPath: prod/postgres/credentials

env:
  SQS_QUEUE_URL: https://sqs.eu-west-2.amazonaws.com/461625527829/prod-ecommerce-orders
  PORT: "8081"
  ORDER_SERVICE_URL: http://order-service:8081
  INVENTORY_SERVICE_URL: http://inventory-service:8082
  PAYMENT_SERVICE_URL: http://payment-service:8083
  NOTIFICATION_SERVICE_URL: http://notification-service:8084
  SHIPPING_SERVICE_URL: http://shipping-service:8085
  DASHBOARD_SERVICE_URL: http://dashboard-api:8086

rollout:
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 2m
      - analysis:
          templates:
            - templateName: success-rate
          args:
            - name: service-name
              value: order-service
      - setWeight: 100