apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-secrets
  namespace: ecommerce-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: order-service-secret
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: {{ .Values.secrets.postgresPath }}
        property: connection-string