apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: {{ .Values.secrets.jwtPath }}
        property: secret
    - secretKey: redis-url
      remoteRef:
        key: {{ .Values.secrets.redisPath }}
        property: url