apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inventory-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: inventory-service-secret
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: {{ .Values.secrets.postgresPath }}
        property: connection-string