replicaCount: 3
image:
  repository: 461625527829.dkr.ecr.eu-west-2.amazonaws.com/prod/inventory-service
  tag: "78a18e46a9e3d62f9364e793d3ec8a67a899c26a"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
service:
  port: 8082
  targetPort: 8082
  protocol: TCP
serviceAccount:
  roleArn: arn:aws:iam::461625527829:role/ecommerce-eks-prod-inventory-service
secrets:
  postgresPath: prod/postgres/credentials
env:
  SQS_QUEUE_URL: https://sqs.eu-west-2.amazonaws.com/461625527829/prod-ecommerce-orders
  PORT: "8082"
