replicaCount: 2
image:
  repository: 461625527829.dkr.ecr.eu-west-2.amazonaws.com/prod/notification-service
  tag: "4cf82b2ab5c07c5ac3b0cf152a89708d41888ab9"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  port: 8084
  targetPort: 8084
  protocol: TCP
secrets:
  postgresPath: prod/postgres/credentials
env:
  PORT: "8084"
