replicaCount: 1
image:
  repository: 461625527829.dkr.ecr.eu-west-2.amazonaws.com/prod/scheduler
  tag: "38c6f48e9964792e5531809c9a359879428b7bd0"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  port: 8091
  targetPort: 8091
  protocol: TCP
secrets:
  postgresPath: prod/postgres/credentials
env:
  HEALTH_PORT: "8091"
