apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbdikarimMHassan/eks-ecommerce-platform
    targetRevision: main
    path: eks-ecommerce-platform/manifest/charts/notification-service
    helm:
      valueFiles:
        - ../../../environments/prod/notification-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true